/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import io.javalin.Javalin;
import io.javalin.config.JavalinConfig;

import java.util.function.Consumer;

import static io.javalin.apibuilder.ApiBuilder.*;

import org.example.controllers.FolderController;
import org.example.controllers.FileController;

import org.jdbi.v3.core.Jdbi;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void config(JavalinConfig config) {
        try {
            Class.forName("org.postgresql.Driver");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
            return;
        }

        /// use a dbPool here instead in the future
        Jdbi jdbi = Database.getJdbi();

        config.appData(Database.dbKey(), jdbi);

        config.router.mount(router -> {
        }).apiBuilder(() -> {
            path("/folders", () -> {
                get(FolderController::getFolder);
                post(FolderController::createFolder);
                put(FolderController::updateFolder);
                path("{folderId}", () -> {
                    delete(FolderController::deleteFolder);
                });
            });
            path("/files", () -> {
                // get(FileController::getFiles);
                post(FileController::createFile);
                path("{fileId}", () -> {
                    get(FileController::getOneFile);
                    patch(FileController::updateFile);
                    delete(FileController::deleteFile);
                });
            });
        });
    }

    public static void main(String[] args) {

        Javalin.create(App::config).start(7070);

    }

    // public Javalin javalinApp() {}
}
