/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.6/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.flywaydb.flyway") version "10.15.0"
}

application {
    mainClass = "org.example.App"
}

repositories {
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    // testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    // implementation(libs.javalin)
    implementation(libs.javalin.bundle)
    implementation(libs.slf4j)
    implementation(libs.jackson)
    implementation(libs.jdbi.core)
    implementation(libs.jdbi.sqlobject)
    implementation(libs.jdbi.postgres)
    implementation(libs.jdbi.jackson)
    implementation(libs.jackson.databind)
    implementation(libs.jackson.annotations)
    implementation(libs.h2database)
    implementation(libs.hikari.cp)
    implementation(libs.postgresql)
    implementation("org.jdbi:jdbi3-stringtemplate4:3.45.1")
    
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.launcher)
    testImplementation(libs.assertj)

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}


// tasks {
//     test {
//         useJUnitPlatform()
//         testLogging.showExceptions = true
//         testLogging.showStackTraces = true
//         // testLogging {
//         //     // events: "passed", "skipped", "failed"
//         // }
//     }

// }

tasks.named<Test>("test") {
    useJUnitPlatform()

    maxHeapSize = "1G"

    testLogging {
        showExceptions = true
        showStackTraces = true
        showStandardStreams = true
        events("passed")
    }

    filter {
        includeTestsMatching("*Test")
    }
}


buildscript {
    dependencies {
        classpath("org.flywaydb:flyway-database-postgresql:10.9.1")

    }
} 

flyway {
    // postgres://{user}:{password}@{hostname}:{port}/{database-name}
    // url = "jdbc:postgresql://tolumide:postgres@localhost:5432/explorer"
    // url = "jdbc:postgresql://localhost:5432/explorer?user=postgres&password=postgres"
    url = "jdbc:postgresql://localhost:5432/explorer"
    driver = "org.postgresql.Driver"
    baselineOnMigrate = true
    locations = arrayOf("filesystem:src/main/resources/db/migration/")
    // locations = arrayOf("classpath:db/migration")
}

